<NotepadPlus>
    <Session activeView="0">
        <mainView activeIndex="8">
            <File firstVisibleLine="0" xOffset="0" scrollWidth="920" startPos="0" endPos="0" selMode="0" lang="JavaScript" encoding="-1" filename="C:\Benjamin espace d&#x00E9;tente\Jeux de soci&#x00E9;t&#x00E9; (cr&#x00E9;ations)\Dragon Ride\Programmation Internet\donnees_statiques.js" backupFilePath="" originalFileLastModifTimestamp="-2090701499" originalFileLastModifTimestampHigh="30728662" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="536901632" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1" startPos="0" endPos="0" selMode="0" lang="JavaScript" encoding="-1" filename="C:\Benjamin espace d&#x00E9;tente\Jeux de soci&#x00E9;t&#x00E9; (cr&#x00E9;ations)\Dragon Ride\Programmation Internet\donnees_statiques_cryptage.js" backupFilePath="" originalFileLastModifTimestamp="1302363714" originalFileLastModifTimestampHigh="30728795" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="16830464" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="600" startPos="0" endPos="0" selMode="0" lang="JavaScript" encoding="-1" filename="C:\Benjamin espace d&#x00E9;tente\Jeux de soci&#x00E9;t&#x00E9; (cr&#x00E9;ations)\Dragon Ride\Programmation Internet\donnees_statiques_fichier.js" backupFilePath="" originalFileLastModifTimestamp="-1200473642" originalFileLastModifTimestampHigh="30728660" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="16830464" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="288" startPos="0" endPos="0" selMode="0" lang="JavaScript" encoding="-1" filename="C:\Benjamin espace d&#x00E9;tente\Jeux de soci&#x00E9;t&#x00E9; (cr&#x00E9;ations)\Dragon Ride\Programmation Internet\donnees_statiques_html.js" backupFilePath="" originalFileLastModifTimestamp="1294254406" originalFileLastModifTimestampHigh="30727258" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="536901632" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1712" startPos="0" endPos="0" selMode="0" lang="JavaScript" encoding="-1" filename="C:\Benjamin espace d&#x00E9;tente\Jeux de soci&#x00E9;t&#x00E9; (cr&#x00E9;ations)\Dragon Ride\Programmation Internet\gameplay.js" backupFilePath="" originalFileLastModifTimestamp="-1204429414" originalFileLastModifTimestampHigh="30730653" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="536901632" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="608" startPos="180" endPos="197" selMode="0" lang="JavaScript" encoding="-1" filename="C:\Benjamin espace d&#x00E9;tente\Jeux de soci&#x00E9;t&#x00E9; (cr&#x00E9;ations)\Dragon Ride\Programmation Internet\global.js" backupFilePath="" originalFileLastModifTimestamp="-354511259" originalFileLastModifTimestampHigh="30730651" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="536901632" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="82" xOffset="0" scrollWidth="808" startPos="2108" endPos="2108" selMode="0" lang="JavaScript" encoding="-1" filename="C:\Benjamin espace d&#x00E9;tente\Jeux de soci&#x00E9;t&#x00E9; (cr&#x00E9;ations)\Dragon Ride\Programmation Internet\htmlUpdate.js" backupFilePath="" originalFileLastModifTimestamp="-1203960676" originalFileLastModifTimestampHigh="30730653" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="536901632" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="21" xOffset="0" scrollWidth="992" startPos="955" endPos="955" selMode="0" lang="JavaScript" encoding="-1" filename="C:\Benjamin espace d&#x00E9;tente\Jeux de soci&#x00E9;t&#x00E9; (cr&#x00E9;ations)\Dragon Ride\Programmation Internet\input.js" backupFilePath="" originalFileLastModifTimestamp="-427103374" originalFileLastModifTimestampHigh="30730653" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="536901632" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="8" startPos="0" endPos="0" selMode="0" lang="JavaScript" encoding="-1" filename="C:\Benjamin espace d&#x00E9;tente\Jeux de soci&#x00E9;t&#x00E9; (cr&#x00E9;ations)\Dragon Ride\Programmation Internet\utils_batiments.js" backupFilePath="" originalFileLastModifTimestamp="-210273954" originalFileLastModifTimestampHigh="30730649" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="536901632" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="6" xOffset="0" scrollWidth="560" startPos="831" endPos="831" selMode="0" lang="JavaScript" encoding="-1" filename="C:\Benjamin espace d&#x00E9;tente\Jeux de soci&#x00E9;t&#x00E9; (cr&#x00E9;ations)\Dragon Ride\Programmation Internet\utils_joueurs_personnages.js" backupFilePath="" originalFileLastModifTimestamp="1707658678" originalFileLastModifTimestampHigh="30730648" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="536901632" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="45" xOffset="0" scrollWidth="1176" startPos="537" endPos="537" selMode="0" lang="JavaScript" encoding="-1" filename="C:\Benjamin espace d&#x00E9;tente\Jeux de soci&#x00E9;t&#x00E9; (cr&#x00E9;ations)\Dragon Ride\Programmation Internet\utils_lieu.js" backupFilePath="" originalFileLastModifTimestamp="2019808150" originalFileLastModifTimestampHigh="30728838" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="536901632" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="512" startPos="319" endPos="319" selMode="0" lang="HTML" encoding="-1" filename="C:\Benjamin espace d&#x00E9;tente\Jeux de soci&#x00E9;t&#x00E9; (cr&#x00E9;ations)\Dragon Ride\Programmation Internet\Dragon Rider.html" backupFilePath="" originalFileLastModifTimestamp="-777169383" originalFileLastModifTimestampHigh="30730648" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="536901632" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="4976" startPos="0" endPos="0" selMode="0" lang="Normal Text" encoding="-1" filename="C:\Benjamin espace d&#x00E9;tente\Jeux de soci&#x00E9;t&#x00E9; (cr&#x00E9;ations)\Dragon Ride\Programmation Internet\Session du jeu" backupFilePath="" originalFileLastModifTimestamp="-491240198" originalFileLastModifTimestampHigh="30730648" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="536901632" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="61" xOffset="0" scrollWidth="320" startPos="1122" endPos="1122" selMode="0" lang="CSS" encoding="-1" filename="C:\Benjamin espace d&#x00E9;tente\Jeux de soci&#x00E9;t&#x00E9; (cr&#x00E9;ations)\Dragon Ride\Programmation Internet\style.css" backupFilePath="" originalFileLastModifTimestamp="216741407" originalFileLastModifTimestampHigh="30730654" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="536901632" mapWrapIndentMode="-1" mapIsWrap="no" />
        </mainView>
        <subView activeIndex="0" />
    </Session>
</NotepadPlus>
